---
title: "Project 2"
author: "Yandong Xiong"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load packages needed
require(tidyverse)
require(dplyr)
require(lubridate)
```

```{r}
setwd("../Data")
lic = read_csv("License_Applications.csv")
legal_b = read_csv("Legally_Operating_Businesses.csv")
```

```{r}
str(lic)
str(legal_b)
```

```{r}
lic%>%count(`License Category`, sort = TRUE)
licence_app = lic %>% mutate(business_type = ifelse(grepl("Cafe", `License Category`), "food_beverage", 
                                            ifelse(grepl("Catering", `License Category`), "food_beverage",
                                                   ifelse(grepl("Amusement", `License Category`), "entertainment",
                                                                 ifelse(grepl("Games", `License Category`), "entertainment",
                                                                        ifelse(grepl("Cabaret", `License Category`), "entertainment",
                                                                               ifelse(grepl("Pool", `License Category`), "entertainment",
                                                                                      ifelse(grepl("Improvement", `License Category`), "service", ifelse(grepl("Sightseeing", `License Category`), "service", ifelse(grepl("Picture", `License Category`), "service", ifelse(grepl("Laundr", `License Category`), "service", ifelse(grepl("Locksmith", `License Category`), "service", ifelse(grepl("Serv", `License Category`), "service", ifelse(grepl("Agency", `License Category`), "service", ifelse(grepl("Garage", `License Category`), "service", ifelse(grepl("Driver", `License Category`), "service", ifelse(grepl("Business", `License Category`), "service", ifelse(grepl("Company", `License Category`), "service", ifelse(grepl("Wash", `License Category`), "service", ifelse(grepl("Tow", `License Category`), "service", ifelse(grepl("Parking", `License Category`), "service", ifelse(grepl("Auction", `License Category`), "service", ifelse(grepl("Pawnbroker", `License Category`), "service", ifelse(grepl("Processor", `License Category`), "service", ifelse(grepl("Owner", `License Category`), "service", ifelse(grepl("Repair", `License Category`), "service", ifelse(grepl("Lessor", `License Category`), "service", ifelse(grepl("Distributor", `License Category`), "service", ifelse(grepl("Storage", `License Category`), "service", "retail")))))))))))))))))))))))))))),
                             ID = gsub("-DCA" , "" ,`License Number`)) %>%
  filter(State == "NY") %>%
  select(ID, name = `Business Name`, end_date = `End Date`, business_type, license_cate = `License Category`, zip = Zip) %>%
  drop_na()
str(licence_app)

head(licence_app)
```


```{r}
legal_business = legal_b %>% mutate(business_type = ifelse(grepl("Cafe", `Industry`), "food_beverage", 
                                            ifelse(grepl("Catering", `Industry`), "food_beverage",
                                                   ifelse(grepl("Amusement", `Industry`), "entertainment",
                                                                 ifelse(grepl("Games", `Industry`), "entertainment",
                                                                        ifelse(grepl("Cabaret", `Industry`), "entertainment",
                                                                               ifelse(grepl("Pool", `Industry`), "entertainment",
                                                                                      ifelse(grepl("Improvement", `Industry`), "service", ifelse(grepl("Sightseeing", `Industry`), "service", ifelse(grepl("Picture", `Industry`), "service", ifelse(grepl("Laundr", `Industry`), "service", ifelse(grepl("Locksmith", `Industry`), "service", ifelse(grepl("Serv", `Industry`), "service", ifelse(grepl("Agency", `Industry`), "service", ifelse(grepl("Garage", `Industry`), "service", ifelse(grepl("Driver", `Industry`), "service", ifelse(grepl("Business", `Industry`), "service", ifelse(grepl("Company", `Industry`), "service", ifelse(grepl("Wash", `Industry`), "service", ifelse(grepl("Tow", `Industry`), "service", ifelse(grepl("Parking", `Industry`), "service", ifelse(grepl("Auction", `Industry`), "service", ifelse(grepl("Pawnbroker", `Industry`), "service", ifelse(grepl("Processor", `Industry`), "service", ifelse(grepl("Owner", `Industry`), "service", ifelse(grepl("Repair", `Industry`), "service", ifelse(grepl("Lessor", `Industry`), "service", ifelse(grepl("Distributor", `Industry`), "service", ifelse(grepl("Storage", `Industry`), "service", "retail")))))))))))))))))))))))))))),
                                    ID = gsub("-DCA" , "" ,`DCA License Number`)) %>%
  filter(`Address State` == "NY") %>%
  select(ID, name = `Business Name`, status = `License Status`, expiration = `License Expiration Date`, business_type, licence_cate = Industry, borough = `Borough Code`, zip = `Address ZIP`) %>%
  drop_na()
str(legal_business)

date = legal_business %>% filter(status == "Active") %>% mutate(expiration = mdy(expiration)) %>% select(expiration)
summary(date)
head(legal_business)
```

```{r}
business_data = left_join(legal_business, licence_app) %>% distinct(ID, .keep_all = TRUE)
head(business_data, 10)
```

```{r}
business_data %>% count(name,sort = TRUE)
```

```{r}
business_data %>% filter(name == "7 ELEVEN INC") %>% count(business_type)
```

