---
title: "Project 2"
author: "Yandong Xiong"
date: "2/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# load packages needed
require(tidyverse)
require(dplyr)
require(lubridate)
```

```{r}
setwd("~/Downloads") # need to be edited as ur working directory
lic = read_csv("License_Applications.csv")
legal_b = read_csv("Legally_Operating_Businesses.csv")

```

```{r}
str(lic)
str(legal_b)
```
```{r}
lic%>%count(`License Category`, sort = TRUE)
licence_app = lic %>% mutate(business_type = ifelse(grepl("Cafe", `License Category`), "food_beverage", 
                                            ifelse(grepl("Catering", `License Category`), "food_beverage",
                                                   ifelse(grepl("Amusement", `License Category`), "entertainment",
                                                                 ifelse(grepl("Games", `License Category`), "entertainment",
                                                                        ifelse(grepl("Cabaret", `License Category`), "entertainment",
                                                                               ifelse(grepl("Pool", `License Category`), "entertainment",
                                                                                      ifelse(grepl("Improvement", `License Category`), "service", ifelse(grepl("Sightseeing", `License Category`), "service", ifelse(grepl("Picture", `License Category`), "service", ifelse(grepl("Laundr", `License Category`), "service", ifelse(grepl("Locksmith", `License Category`), "service", ifelse(grepl("Serv", `License Category`), "service", ifelse(grepl("Agency", `License Category`), "service", ifelse(grepl("Garage", `License Category`), "service", ifelse(grepl("Driver", `License Category`), "service", ifelse(grepl("Business", `License Category`), "service", ifelse(grepl("Company", `License Category`), "service", ifelse(grepl("Wash", `License Category`), "service", ifelse(grepl("Tow", `License Category`), "service", ifelse(grepl("Parking", `License Category`), "service", ifelse(grepl("Auction", `License Category`), "service", ifelse(grepl("Pawnbroker", `License Category`), "service", ifelse(grepl("Processor", `License Category`), "service", ifelse(grepl("Owner", `License Category`), "service", ifelse(grepl("Repair", `License Category`), "service", ifelse(grepl("Lessor", `License Category`), "service", ifelse(grepl("Distributor", `License Category`), "service", ifelse(grepl("Storage", `License Category`), "service", "retail")))))))))))))))))))))))))))),
                             ID = gsub("-DCA" , "" ,`License Number`)) %>%
  filter(State == "NY") %>%
  select(ID, name = `Business Name`, new_renewl = `Application or Renewal`, start_date = `Start Date`,end_date = `End Date`, business_type, license_cate = `License Category`, zip = Zip) %>%
  drop_na()
str(licence_app)

```


```{r}

legal_business = legal_b %>% mutate(business_type = ifelse(grepl("Cafe", `Industry`), "food_beverage", 
                                            ifelse(grepl("Catering", `Industry`), "food_beverage",
                                                   ifelse(grepl("Amusement", `Industry`), "entertainment",
                                                                 ifelse(grepl("Games", `Industry`), "entertainment",
                                                                        ifelse(grepl("Cabaret", `Industry`), "entertainment",
                                                                               ifelse(grepl("Pool", `Industry`), "entertainment",
                                                                                      ifelse(grepl("Improvement", `Industry`), "service", ifelse(grepl("Sightseeing", `Industry`), "service", ifelse(grepl("Picture", `Industry`), "service", ifelse(grepl("Laundr", `Industry`), "service", ifelse(grepl("Locksmith", `Industry`), "service", ifelse(grepl("Serv", `Industry`), "service", ifelse(grepl("Agency", `Industry`), "service", ifelse(grepl("Garage", `Industry`), "service", ifelse(grepl("Driver", `Industry`), "service", ifelse(grepl("Business", `Industry`), "service", ifelse(grepl("Company", `Industry`), "service", ifelse(grepl("Wash", `Industry`), "service", ifelse(grepl("Tow", `Industry`), "service", ifelse(grepl("Parking", `Industry`), "service", ifelse(grepl("Auction", `Industry`), "service", ifelse(grepl("Pawnbroker", `Industry`), "service", ifelse(grepl("Processor", `Industry`), "service", ifelse(grepl("Owner", `Industry`), "service", ifelse(grepl("Repair", `Industry`), "service", ifelse(grepl("Lessor", `Industry`), "service", ifelse(grepl("Distributor", `Industry`), "service", ifelse(grepl("Storage", `Industry`), "service", "retail")))))))))))))))))))))))))))),
                                    ID = gsub("-DCA" , "" ,`DCA License Number`),
                                    `Borough Code` = ifelse(`Borough Code` == 1, "Manhattan",
                                                            ifelse(`Borough Code` == 2, "Bronx",
                                                                   ifelse(`Borough Code` == 3, "Brooklyn",
                                                                          ifelse(`Borough Code` == 4, "Queens",
                                                                                 ifelse(`Borough Code` == 5, "Staten Island", NA)))))) %>%
  filter(`Address State` == "NY") %>%
  select(ID, name = `Business Name`, status = `License Status`, creation = `License Creation Date`, expiration = `License Expiration Date`, business_type, licence_cate = Industry, borough = `Borough Code`, zip = `Address ZIP`) %>%
  drop_na()
str(legal_business)

date = legal_business %>% filter(status == "Active") %>% mutate(expiration = mdy(expiration)) %>% select(expiration)
summary(date)
```

```{r}
business_data = left_join(legal_business, licence_app) %>% distinct(ID, .keep_all = TRUE)
new_bus_reta = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "retail")
new_bus_serv = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "service")
new_bus_f_b = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "food_beverage")
new_bus_ent = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "entertainment")
data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), borough == "Staten Island")
data = data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = ""))
plot(data$n, type = "o", pch = 22, lty = 1, pty = 2, 
         ylab = "monthly new business", 
         main = "New business created by month from 2019 to 2020")
axis.Date(1, at=seq(as.Date("01-01-2019"), as.Date("12-01-2020"), by="months"), format="%m-%Y")
plot(n ~ as.Date(date), data, xaxt = "n", type = "o", pch = 22, lty = 1, pty = 2)
abline(v = c(as.Date("2020/03/01","%Y/%m/%d"), 
             as.Date("2020/06/01","%Y/%m/%d"),
             as.Date("2020/07/01","%Y/%m/%d"),
             as.Date("2020/09/01","%Y/%m/%d")), 
       col = c("red","purple","green","blue"))
legend("topright", legend=c("Non Essentials Stay Home", "Phase 1 & 2 Reopening",
                            "Phase 2 & 3 Reopening", "Phase 4 Reopening"),
       col=c("red","purple","green","blue"), lty=1, cex=0.8)
axis.Date(1, at = data$date, format= "%m-%Y", las = 1)
#abline(v = format(as.Date("2019/12/01","%Y/%m/%d"), "%m-%Y"))
```


```{r}
# Define UI ----
ui <- fluidPage(

  # App title ----
  titlePanel("New Business"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Select for the borough ----
      selectInput(inputId = "borough",
                  label = "Choose a borough:",
                  choices = c("Manhattan", "Bronx", "Brooklyn", "Queens", "Staten Island")),
      
      # Input: Select for the business type ----
      selectInput(inputId = "business_type",
                  label = "Choose a business type:",
                  choices = c("retail", "service", "food and beverage", "entertainment"))

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: tsPlot on borough ----
      plotOutput(outputId = "tsPlot1"),
      
      # Output: tsPlot on business type ----
      plotOutput(outputId = "tsPlot2")

    )
  )
)

# Define server ----
server <- function(input, output) {
  
  business_type_data <- reactive({
    if ( "retail" %in% input$business_type){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "retail")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = ""))) 
    }
    if ( "service" %in% input$business_type){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "service")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
    if ( "food and beverage" %in% input$business_type){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "food_beverage")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
    if ( "entertainment" %in% input$business_type){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), business_type == "entertainment")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
  })
  
  borough_data <- reactive({
    if ( "Manhattan" %in% input$borough){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), borough == "Manhattan")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = ""))) 
    }
    if ( "Bronx" %in% input$borough){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), borough == "Bronx")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
    if ( "Brooklyn" %in% input$borough){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), borough == "Brooklyn")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
    if ( "Queens" %in% input$borough){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), borough == "Queens")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
    if ( "Staten Island" %in% input$borough){
      data = business_data %>% filter(grepl("2020", creation) | grepl("2019", creation), borough == "Staten Island")
      return(data %>% count(date = format(as.Date(creation, format = "%m/%d/%Y"), "%Y/%m")) %>% mutate(date = paste(date,"/01", sep = "")))
    }
  })
  
  output$tsPlot1 <- renderPlot({
    data = borough_data()
    plot(n ~ as.Date(date), data, xaxt = "n", type = "o", pch = 22, lty = 1, pty = 2, 
         ylab = "monthly new business", xlab = "",
         main = paste("Number of new business created in ",  input$borough, " from 2019 to 2020"))
    axis.Date(1, at = data$date, format= "%m-%Y", las = 1)
  })
  
  output$tsPlot2 <- renderPlot({
    data = business_type_data()
    plot(n ~ as.Date(date), data, xaxt = "n", type = "o", pch = 22, lty = 1, pty = 2, ylab = "monthly new business", xlab = "",
         main = paste("Number of ",  input$business_type, " business created in NYC from 2019 to 2020"))
    axis.Date(1, at = data$date, format= "%m-%Y", las = 1)
  })
}

shinyApp(ui, server)
```

